# Setup
title:        Tops Product Locator
tagline:      A mobile/web application to locate products in Tops Friendly Market stores
baseurl:      "~topteam"
locale:       "en"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

#Others
markdown: kramdown
